[build]
  command = "bash build.sh"
  functions = "netlify/functions"
  publish = "netlify/static"

# Simple redirect for the API test endpoint
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

# Root path redirect to the index function
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

# Catch-all redirect for all other paths
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[functions.main]
  runtime = "python3.8"
