[build]
command = "bash build.sh"
functions = "netlify/functions"
publish = "netlify/static"

[functions]
python_version = "3.8"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
