[build]
  command = "bash build.sh"
  functions = "netlify/functions"
  publish = "netlify/static"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[functions.main]
  runtime = "python3.11"
